### ISSUE TITLE
迁移到这个主题报错

### ISSUE THREAD

**Issue by zhixiangyuan** [xzzai/halo-theme-xue#28]
# 系统版本

```
版本：1.4.0-beta.2
数据库：H2 1.4.196 (2017-06-10)
运行模式：production
User Agent：Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.105 Safari/537.36
```

# 主题版本

```
1.1.5
```

# 报错信息

![image](https://user-images.githubusercontent.com/25138766/89605790-fe3d0400-d8a0-11ea-8cac-112e583e8ec3.png)

**Comment by xzzai** [comment]
你是直接更新的吗？还是作为一个新主题导入的？

**Comment by zhixiangyuan** [comment]
> 你是直接更新的吗？还是作为一个新主题导入的？

作为一个新主题导入的

**Comment by xzzai** [comment]
我先下去看下，目前还不能确定是什么问题

**Comment by zhixiangyuan** [comment]
> 我先下去看下，目前还不能确定是什么问题

好的，大大解决了叫我一声，感谢

**Comment by zhixiangyuan** [comment]
> 我先下去看下，目前还不能确定是什么问题

这是详细报错日志

```
Caused by: freemarker.core._MiscTemplateException: Template inclusion failed (for parameter value "module/macro.ftl"):
Template not found for name "themes/bao/module/macro.ftl".
The name was interpreted by this TemplateLoader: MultiTemplateLoader(loader1 = FileTemplateLoader(baseDir="/root/.halo/templates", canonicalBasePath="/root/.halo/templates/"), loader2 = org.springframework.ui.freemarker.SpringTemplateLoader@195b284c, loader3 = ClassTemplateLoader(resourceLoaderClass=org.springframework.web.servlet.view.freemarker.FreeMarkerConfigurer, basePackagePath="" /* relatively to resourceLoaderClass pkg */)).

----
FTL stack trace ("~" means nesting-related):
	- Failed at: #include "module/macro.ftl"  [in template "themes/bao/index.ftl" at line 1, column 1]
----
	at freemarker.core.Include.accept(Include.java:164) ~[freemarker-2.3.30.jar!/:2.3.30]
	at freemarker.core.Environment.visit(Environment.java:334) ~[freemarker-2.3.30.jar!/:2.3.30]
	at freemarker.core.Environment.visit(Environment.java:340) ~[freemarker-2.3.30.jar!/:2.3.30]
	at freemarker.core.Environment.process(Environment.java:313) ~[freemarker-2.3.30.jar!/:2.3.30]
	at freemarker.template.Template.process(Template.java:383) ~[freemarker-2.3.30.jar!/:2.3.30]
	at org.springframework.web.servlet.view.freemarker.FreeMarkerView.processTemplate(FreeMarkerView.java:391) ~[spring-webmvc-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
	at org.springframework.web.servlet.view.freemarker.FreeMarkerView.doRender(FreeMarkerView.java:304) ~[spring-webmvc-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
	at org.springframework.web.servlet.view.freemarker.FreeMarkerView.renderMergedTemplateModel(FreeMarkerView.java:255) ~[spring-webmvc-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
	at org.springframework.web.servlet.view.AbstractTemplateView.renderMergedOutputModel(AbstractTemplateView.java:179) ~[spring-webmvc-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
	at org.springframework.web.servlet.view.AbstractView.render(AbstractView.java:316) ~[spring-webmvc-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.render(DispatcherServlet.java:1373) ~[spring-webmvc-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.processDispatchResult(DispatcherServlet.java:1118) ~[spring-webmvc-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1057) ~[spring-webmvc-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:943) ~[spring-webmvc-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006) ~[spring-webmvc-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
	... 58 common frames omitted
Caused by: freemarker.template.TemplateNotFoundException: Template not found for name "themes/bao/module/macro.ftl".
The name was interpreted by this TemplateLoader: MultiTemplateLoader(loader1 = FileTemplateLoader(baseDir="/root/.halo/templates", canonicalBasePath="/root/.halo/templates/"), loader2 = org.springframework.ui.freemarker.SpringTemplateLoader@195b284c, loader3 = ClassTemplateLoader(resourceLoaderClass=org.springframework.web.servlet.view.freemarker.FreeMarkerConfigurer, basePackagePath="" /* relatively to resourceLoaderClass pkg */)).
	at freemarker.template.Configuration.getTemplate(Configuration.java:2869) ~[freemarker-2.3.30.jar!/:2.3.30]
	at freemarker.core.Environment.getTemplateForInclusion(Environment.java:2883) ~[freemarker-2.3.30.jar!/:2.3.30]
	at freemarker.core.Include.accept(Include.java:162) ~[freemarker-2.3.30.jar!/:2.3.30]
	... 72 common frames omitted
```

**Comment by xzzai** [comment]
我自己下下来试了下，发现是可以的

**Comment by xzzai** [comment]
你试一下 最新版本，看下可以不

**Comment by zhixiangyuan** [comment]
> 你试一下 最新版本，看下可以不

可以了，大佬牛逼
